### ISSUE TITLE
On final button presses to add offer, a double click is done that is clicking purchase after add

### ISSUE THREAD

**Issue by Haldim** [matthewmiglio/py-TarkBot#21]
This issue only exists for items with full pages of listings.  The purchase window will stop the offer from being put up for listing.

**Comment by matthewmiglio** [comment]
It's not actually purchasing, right?

**Comment by marmig0404** [comment]
I've seen this occur, it does not actually purchase the item, just selects the purchase button and then the confirmation prompt pops up in the way, hindering the bot.

**Comment by Haldim** [comment]
Copy that, exactly as marmig says.  Just getting hung up, will not complete the purchase in the prompt.

**Comment by matthewmiglio** [comment]
The underlying issue is a patch I made a few months ago. I removed the buggy patch and hopefully also fixed the underlying issue that necessitated the patch.

These updates are available under the new v0.2.7 release.

I'm closing the issue as the original problem is fixed. If this new version has another issue please open a separate issue.
