### ISSUE TITLE
too many errors when reading the flea market price. digit is empty error

### ISSUE THREAD

**Issue by DatGuyRobo** [matthewmiglio/py-TarkBot#30]

**Comment by marmig0404** [comment]
Does this result in the bot reading the values wrong or actual runtime errors stopping the progression of the bot? If it's runtime errors, could you share them?

**Comment by DatGuyRobo** [comment]
Bot is reading the number wrong or can’t recognize it

**Comment by marmig0404** [comment]
Yeah, that's going to be an issue for now. We're investigating ways to make it more reliable but that's going to require a custom tesseract model trained on Tarkov's fonts.

**Comment by DatGuyRobo** [comment]
Or look into #34 if the font are bigger maybe the recognition is better

**Comment by matthewmiglio** [comment]
This is an issue only because it's particularly difficult to test the reading of this value. 

My one Tarkov account only has one rouble count and it's a pretty stagnant one at that. As such, I'm unable to test a wide range of values for my money reading function (I'm not going to go broke nor grind to 12M just to debug my function).

Because of this, I won't be able to fix this with my current setup anytime soon, so I will probably un-do these statistics' implementation,
